apiVersion: v1
kind: Namespace
metadata:
  name: pulceo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulceo-node-agent
  namespace: pulceo
  labels:
    app: pulceo-node-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulceo-node-agent
  template:
    metadata:
      labels:
        app: pulceo-node-agent
    spec:
      containers:
        - name: pulceo-node-agent
          image: nginx:1.14.2
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: pulceo
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: nginx:1.14.2
          ports:
            - containerPort: 80
