apiVersion: v1
kind: Service
metadata:
  name: pulceo-node-agent
spec:
  ports:
    - name: web
      port: 7676
      targetPort: web
    - name: web5000
      port: 5000
      targetPort: iperf5000
    - name: web5001
      port: 5001
      targetPort: iperf5001
    - name: web5002
      port: 5002
      targetPort: iperf5002
    - name: web5003
      port: 5003
      targetPort: iperf5003
    - name: web5004
      port: 5004
      targetPort: iperf5004
    - name: web5005
      port: 5005
      targetPort: iperf5005
  selector:
    app: pulceo-node-agent
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pulceo-node-agent
  labels:
    app: pulceo-node-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulceo-node-agent
  template:
    metadata:
      labels:
        app: pulceo-node-agent
    spec:
      containers:
        - name: pulceo-node-agent
          image: ghcr.io/spboehm/pulceo-node-agent:v1.3.0
          volumeMounts:
            - mountPath: /k3s.yaml
              name: k3s
              readOnly: true
          imagePullPolicy: Always
          env:
            - name: PNA_LOCAL_ADDRESS
              value: "0.0.0.0"
          ports:
            - containerPort: 7676
              name: web
            - containerPort: 5000
              name: iperf5000
            - containerPort: 5001
              name: iperf5001
            - containerPort: 5002
              name: iperf5002
            - containerPort: 5003
              name: iperf5003
            - containerPort: 5004
              name: iperf5004
            - containerPort: 5005
              name: iperf5005
      volumes:
        - name: k3s
          hostPath:
            path: ./k3s.yaml
            type: File
