piVersion: v1
kind: Service
metadata:
  name: pulceo-node-agent
spec:
  ports:
    - name: web
      port: 7676
      targetPort: web
  selector:
    app: pulceo-node-agent
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pulceo-node-agent
  labels:
    app: pulceo-node-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulceo-node-agent
  template:
    metadata:
      labels:
        app: pulceo-node-agent
    spec:
      containers:
        - name: pulceo-node-agent
          image: ghcr.io/spboehm/pulceo-node-agent:cpu-util
          imagePullPolicy: Always
          env:
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
          ports:
            - containerPort: 7676
              name: web
