name: Build pulceo-node-agent

on:
  push:

jobs:
  build-gradle-project:
    runs-on: self-hosted
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build