name: Build pulceo-node-agent

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare:
    runs-on: self-hosted
    steps:
      - name: Spin up k3d cluster
        run: k3d cluster create pna-test --k3s-arg "--disable=traefik@server:0" --port 8080:80@loadbalancer
  build:
    needs: prepare
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Copy k3s.yaml
        run: cp /home/$USER/.kube/config $GITHUB_WORKSPACE/.k3s.yaml
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
  build-and-push-image:
    needs: build
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  teardown:
    if: ${{ always() }}
    needs: [ prepare, build, build-and-push-image ]
    runs-on: self-hosted
    steps:
      - name: Teardown k3d cluster
        run: k3d cluster delete pna-test
